@startuml configd-flow

!theme blueprint
skinparam BoxPadding 10
skinparam dpi 200
skinparam backgroundcolor transparent

participant "Some device" as Client
participant Syncthing as Server
participant "configd" as configd

activate Server
Client -> Server : Connect
note over Server
    Unknown device
    is rejected
end note
return Rejected

Server -> configd : "Device Rejected" event
activate configd
configd -> Server : Add device
note right
    configd applies rules
    and patterns based on
    source address
end note
configd -> Server : Add folders
deactivate configd

activate Client
Client -> Server : Connect
note over Server
    Known device
    is accepted
end note
Server -> Client : Accepted

@enduml
